### ISSUE TITLE
LinearGradinet not work in Android.

### ISSUE THREAD

**Issue by antoxi4** [magicismight/react-native-art-svg#1]
Hey, i try use Your module, but LinearGradient work only on IOS.
Can You help me?

**Comment by magicismight** [comment]
@antoxi4 

This library is based on React Native\`s ART, and this feature is not supported by ART right now.
See [#5510](https://github.com/facebook/react-native/issues/5510)
We can just wait for the [official fix](https://github.com/facebook/react-native/pull/5729) landed on ART.

BTW: Sorry for not replying this in time,I was on vocation.

**Comment by magicismight** [comment]
Oh.
That PR mentioned before is the one you sended.
Thanks for this. hope it would landed on ART soon.
:+1:

**Comment by gordonpro** [comment]
@magicismight is the ART means system `ART Runtime mode`?

**Comment by magicismight** [comment]
@gordonpro  [ReactART](https://github.com/reactjs/react-art)

**Comment by magicismight** [comment]
Get it fixed bases on your PR.
But `react-native-art-svg` on the npm has changed to `react-native-svg`.
And it is no longer using ReactNativeArt as its dependency, you have to link the native code inside `react-native-svg`
