### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by ajoshdee** [magicismight/react-native-art-svg#19]
Hi, I tried updating but i always get this warning ,
Warning: Native component for "RNSVGSvgView" does not exist

**Comment by magicismight** [comment]
`react-native-svg` no longer use ART as dependency now.
You should [link](http://facebook.github.io/react-native/docs/linking-libraries-ios.html#content) the native code inside. 
Or use rnpm: `rnpm link`

**Comment by ajoshdee** [comment]
Does this support cocoapods?

**Comment by magicismight** [comment]
No.
Just support rnpm for now

**Comment by ajoshdee** [comment]
Maybe you could include it in next update.

**Comment by magicismight** [comment]
Yep.
It`s a good idea.
But I`m not so familiar with cocoapods.I`ll try this later.

**Comment by WillCoco** [comment]
hi, how make it works with android，i got a warning ，
Warning: Native component for "RNSVGSvgView" does not exist
