### ISSUE TITLE
Symbol.js TransformError with react native v0.20

### ISSUE THREAD

**Issue by tuantle** [magicismight/react-native-art-svg#2]
react-native-art-svn Symbol.js won't compile with latest react version. Seems like a babel syntax issue.

TransformError: ..../node_modules/react-native-art-svg/elements/Symbol.js: ..../node_modules/react-native-art-svg/elements/Symbol.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "ConditionalExpression"

**Comment by magicismight** [comment]
Thanks for informing this.
It`s fixed in [there](https://github.com/magicismight/react-native-art-svg/commit/2131e7bc1eb36151f3dd5ebe489e3dac747ccd38)
