### ISSUE TITLE
Circle not visible in iOS, ok for Android, Ellipse ok on both

### ISSUE THREAD

**Issue by pietgk** [magicismight/react-native-art-svg#27]
I tried the Readme example SVG on android and ios.
The strange effect is that the below Ellipse works on both,
but the Circle is only displayed on android.

    <Svg height="100" width="100">
      <Ellipse cx="50" cy="50" rx="45" ry="45" fill="yellow" />
    </Svg>

    <Svg height="100" width="100">
      <Circle cx="50" cy="50" r="45" fill="yellow" />
    </Svg>

Any hints on why this is the case?

i am using "react-native-svg": "^1.2.2",

**Comment by magicismight** [comment]
I see.
This have been fixed.
Thanks for reporting this.

**Comment by magicismight** [comment]
Fix will be released to npm tomorrow.
I`m closing this issue now.
