### ISSUE TITLE
Circle not drawing

### ISSUE THREAD

**Issue by ericsoderberghp** [magicismight/react-native-art-svg#28]
I can't seem to render Circles, either fill or stroke. I am using react-native-svg 1.2.2 installed according to the README. When I try the first example combining a Circle and a Rect, I see the yellow Rect with a red border but I don't see any Circle.

**Comment by magicismight** [comment]
Thx for reporting this.
This has been fixed in [1.2.3](https://github.com/magicismight/react-native-art-svg/commit/12c38d76045f7eff35923f6a42b8f277c3c36b84)

**Comment by ericsoderberghp** [comment]
Thanks.
