### ISSUE TITLE
My illustrator-exported path doesn't work: JSON value '<null>' of type NSNULL canot be converted to NSNumber (iOS)

### ISSUE THREAD

**Issue by faceyspacey** [magicismight/react-native-art-svg#29]
Here's my code:

```
<Svg height="100" width="100">
   <Path fill='red' d="M38.459,1.66A0.884,0.884,0,0,1,39,2.5a0.7,0.7,0,0,1-.3.575L23.235,16.092,27.58,26.1a1.4,1.4,0,0,1,.148.3,1.3,1.3,0,0,1,0,.377,1.266,1.266,0,0,1-2.078.991L15.526,20.6l-7.58,4.35a1.255,1.255,0,0,1-.485,0,1.267,1.267,0,0,1-1.277-1.258q0-.01,0-0.02a1.429,1.429,0,0,1,0-.446C7.243,20.253,8.6,16.369,8.6,16.29L3.433,13.545A0.743,0.743,0,0,1,2.9,12.822a0.822,0.822,0,0,1,.623-0.773l8.164-2.972,3.018-8.5A0.822,0.822,0,0,1,15.427,0a0.752,0.752,0,0,1,.752.555l2.563,6.936S37.65,1.727,37.792,1.685A1.15,1.15,0,0,1,38.459,1.66Z"/>
</Svg>
```

The path is exported from illustrator. I've tried transforming it with `svgo`, I've tried every export option. Simpler paths work, but this path of a rounded star shape does not. The path works when exported to a browser and in `react-mt-svg-lines` for the browser, but not in iOS using React Native and this package. 

It just feels like it's getting overloaded with the amount of directions in the path since easier paths are working. Any ideas?

**Comment by faceyspacey** [comment]
if I remove the decimals all the way down to zero decimals it works, but even with one decimal (as exported from Illustrator) it gets this issue. I wish I could use the 1 decimal version but it's far from good enough--what could be wrong with these numbers?

**Comment by magicismight** [comment]
It\`s a bug while serializing path.
It will go wrong while process something like this: `1-2.078.991`
But got it been fixed in `1.2.4`
Thx for reporting this.

**Comment by tuneZola** [comment]
I am having the same issue with long path data. Is 1.2.4 version out yet?

**Comment by tuneZola** [comment]
Example
`
<Svg height="100" width="100">
   <Path fill='red' d="M6.5 1C7.9 1 9 2.1 9 3.5c0 .8-.4 1.6-1.1 2.1-.4.2-.9.4-1.4.4s-1-.2-1.4-.4C4.4 5.1 4 4.3 4 3.5 4 2.1 5.1 1 6.5 1m0-1C4.6 0 3 1.6 3 3.5c0 1.2.6 2.2 1.5 2.9.6.4 1.3.6 2 .6s1.4-.2 2-.6c.9-.7 1.5-1.7 1.5-2.9C10 1.6 8.4 0 6.5 0zm3.6 8.9c.6.8.9 1.7.9 2.6v.5H2v-.5c0-1 .3-1.9.9-2.6 1 .7 2.3 1.1 3.6 1.1s2.6-.4 3.6-1.1m.2-1.4C9.3 8.4 8 9 6.5 9s-2.8-.6-3.8-1.5c-1.1 1-1.7 2.4-1.7 4 0 .5.1 1.5.2 1.5h10.6c.1 0 .2-1 .2-1.5 0-1.6-.7-3-1.7-4z"/>
</Svg>
`

Its mostly having issues at SerializablePath.curve method which appears to hot parse the values correctly in most cases. x + (+c1x) and y + (+c1y) evaluate to NaN often. You check for isNil, but what are you doing for cases in which it is not a number? And are you relying on implicit conversion for floats, ints etc?
