### ISSUE TITLE
Gradients not rendering in Android React Native 0.20.0

### ISSUE THREAD

**Issue by AlexDM0** [magicismight/react-native-art-svg#5]
Hi,

I cannot seem to render the gradients in react Native 0.20.0

![error_example](https://cloud.githubusercontent.com/assets/5363277/13258050/c9b85d94-da51-11e5-8d17-e1e251090a6c.png)

The screenshot is taken from your example. Any ideas?

Regards

**Comment by magicismight** [comment]
Thanks for reporting this issue.
gradients only supports iOS for now.It won`t work on Android util [this](https://github.com/facebook/react-native/pull/5729) be merged into react-native
Also see [#5510](https://github.com/facebook/react-native/issues/5510)

**Comment by AlexDM0** [comment]
Hi thanks for your reply. The pull only seems to cover linearGradients, though I was mainly interested in the radial ones. 

Are you also going to try to pull this into react native? It would be great if it was in the native repo!

Cheers

**Comment by magicismight** [comment]
Sorry, I\`m not familiar with native code on Android.
I can not help you with that.
We can just wait the official fix for this.
But it seems like they are not so interested in ART,there are lots of `TODO`s in ART code.
And they are never changed since ART is being open sourced

**Comment by AlexDM0** [comment]
I see, fair enough. Thanks for the quick replies!

I think I'll have to go for and SVG solution that's not based on ART then.. 

You can close this issue if you want, though I'd recommend putting a notification in your read me for others :). 

Cheers

**Comment by magicismight** [comment]
It has been fixed now.
But `react-native-art-svg` on the npm has changed to `react-native-svg`
And it is no longer using ReactNativeArt as its dependency, you have to link the native code inside `react-native-svg`

**Comment by AlexDM0** [comment]
Awesome! Thanks!
