### ISSUE TITLE
Dashed paths not working in Android

### ISSUE THREAD

**Issue by Svajoklis-** [magicismight/react-native-art-svg#8]
Paths that have "strokeDasharray" specified show up as solid. The same prop works fine on iOS.

**Comment by magicismight** [comment]
Yep..
ART do not support this feature on Android right now.

**Comment by magicismight** [comment]
Finished this feature in `react-native-svg@1.1.0`
You can change the package name from `react-native-art-svg` to `react-native-svg`, and link the native code inside,this will work.

**Comment by Svajoklis-** [comment]
Thanks!
